### ISSUE TITLE
Works with Matlab on Travis

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [MOxUnit/MOxUnit#64]
So, travis [added support for native matlab](https://docs.travis-ci.com/user/languages/matlab/) recently (only R2020a and higher and only on linux). I've had a go at setting it up (in [this](https://github.com/MarcinKonowalczyk/poly-fast-matlab) repository) and it *does* indeed work with MOxUnit. Hooray! 😄 

There are some issues I've encoutered. The make file dies during `matlab-install` with error code 1 aka 'something went wrong'. I thought of patching it with a pole of echos to actually see what commands are beeing run, but I think it's actually that calling a typical `matlab -nodesktop -nosplash ...` command does not work in this case. What *did* work is the '-batch' command line option (not sure where it's documented except for [here](https://docs.travis-ci.com/user/languages/matlab/)). Here is what my `.travis.yml` looks like:

```yml
language: matlab
matlab: R2020a
before_script:
  - git clone https://github.com/MOxUnit/MOxUnit.git
script:
  - matlab -batch 'back=cd("./MOxUnit/MOxUnit/"); moxunit_set_path(); cd(back); moxunit_runtests tests -verbose; exit(double(~ans))'
```

The `exit(double(~ans))` nonsence makes sure that when the `moxunit_runtests tests -verbose` fails, the whole command fails. Otherwise it would print the failure, but do nothing about it.
